import Contact from "@/components/Contact";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import 'remixicon/fonts/remixicon.css'
import AboutUs from "@/components/AboutUs";


export default function Home() {
  return (
    <>
      <Head>
        <title>Nac Bilişim Teknoloji</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    
        
        <Contact/>
        <AboutUs/>
      
   
      
    </>
  );
}
